### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iostyle** [Jon-Millent/irest#1]
/usr/local/lib/node_modules/irest-cli/node_modules/images/scripts/util/binding.js:20
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /usr/local/lib/node_modules/irest-cli/node_modules/images/vendor/darwin-x64-57/binding.node
images could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild images --force` to build the binding for your current environment.
    at module.exports (/usr/local/lib/node_modules/irest-cli/node_modules/images/scripts/util/binding.js:20:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/irest-cli/node_modules/images/index.js:32:51)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/irest-cli/module/image.js:7:14)

**Comment by iostyle** [comment]
node --version
v8.12.0

**Comment by Jon-Millent** [comment]
你好，感谢反馈bug。这问题已经解决，我发布了新版本的包。请卸载后重装一下。
```
sudu npm uninstall -g ires-cli
```

```
sudu npm install -g ires-cli
```

**Comment by iostyle** [comment]
看了你的网站 我觉得该叫 cmdgays 😄
